import {StyleSheet} from 'react-native';

const homeStyles = StyleSheet.create({
  main: {
    marginTop: 27,
    marginHorizontal: 20,
    width: '90%',
    height: 224,
    borderRadius: 8,
  },
  Findr: {
    color: '#5B59FE',
    marginTop: 8,
    fontFamily: 'Familjen Grotesk',
    fontSize: 64,
    fontWeight: '700',
    lineHeight: 77,
    textAlign: 'center',
  },
  searchForHope: {
    width: 115,
    height: 24,
    marginLeft: 185,
    marginRight: 105,
    marginTop: -20,
  },
  search: {
    width: 19,
    height: 19,
    marginLeft: 185,
    marginRight: 9,
    marginTop: 0,
  },
  searchinput: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 285,
    height: 40,
    marginLeft: 53,
    marginRight: 63,
    marginTop: 26,
    borderWidth: 1,
    borderColor: '#0F0F0F',
    borderRadius: 8,
  },
  color: {
    color: 'white',
  },
  main2: {
    width: 365,
    height: 304,
    borderRadius: 8,
    marginRight: 16,
    flexDirection: 'row',
    gap: 10,
    marginLeft: 20,
  },
  imageBackground: {
    width: 213,
    height: 260,
  },
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 16,
  },
  mainView: {
    width: 213,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#CC4141',
    marginRight: 16,
  },
  mainHeading: {
    width: 160,
    height: 38,
    paddingTop: 2,
    paddingLeft: 31,
    fontWeight: '400',
    marginBottom: 3,
    fontSize: 32,
    color: '#FFFFFF',
  },
  buttontext: {
    marginVertical: 5,
    textAlign: 'center',
    color: 'white',
    fontWeight: '500',
    fontSize: 11,
  },
  button: {
    backgroundColor: '#5B59FE',
    marginTop: 15,
    borderRadius: 8,
    width: 95,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  cancel: {
    width: 10,
    height: 10,
    marginLeft: 308,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 23,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  emailtext: {
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    color: '#5B59FE',
    fontWeight: '500',
    fontSize: 11,
    paddingHorizontal: 70,
  },
  email: {
    backgroundColor: 'white',
    marginLeft: 18,
    marginRight: 17,
    marginTop: 112,
    borderRadius: 8,
    borderColor: '#5B59FE',
    borderWidth: 1,
  },
  reporttext: {
    marginTop: 10,
    marginBottom: 10,
    textAlign: 'center',
    color: 'white',
    fontWeight: '500',
    fontSize: 11,
    paddingHorizontal: 80,
  },
  report: {
    backgroundColor: '#5B59FE',
    marginLeft: 18,
    marginRight: 17,
    marginTop: 16,
    borderRadius: 8,
  },
  personpopup: {
    width: 100,
    height: 100,
    marginTop: 24,
    marginLeft: 118,
    marginRight: 117,
    marginBottom: 16,
    borderRadius: 200,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default homeStyles;
