import {StyleSheet} from 'react-native';
const loginStyles = StyleSheet.create({
  Findr: {
    color: '#5B59FE',
    marginTop: 70,
    fontFamily: 'Familjen Grotesk',
    fontSize: 64,
    fontWeight: '700',
    lineHeight: 77,
    textAlign: 'center',
  },
  searchForHope: {
    width: 115,
    height: 24,
    marginLeft: 185,
    marginRight: 105,
    marginTop: -20,
  },
  mainheading1: {
    fontFamily: 'Familjen Grotesk',
    marginLeft: 39.5,
    marginTop: 24,
    marginRight: 39.5,
    fontSize: 40,
    lineHeight: 54,
    color: '#0F0F0F',
    fontWeight: '700',
  },
  headinginput1: {
    color: '#121212',
    width: 40,
    marginTop: 24,
    marginLeft: 33,
    height: 20,
    fontFamily: 'Familjen Grotesk',
    lineHeight: 27.6,
    textAlign: 'center',
  },
  headinginput2: {
    color: '#121212',
    width: 70,
    marginTop: 24,
    marginLeft: 33,
    height: 20,
    fontFamily: 'Familjen Grotesk',
    lineHeight: 27.6,
    textAlign: 'center',
  },
  firstinput: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 310,
    marginLeft: 33,
    marginRight: 34,
    marginTop: 5,
    borderWidth: 1,
    borderColor: '#D0D5DD',
    borderRadius: 8,
  },
  secondinput: {
    padding: 12,
    marginTop: 6,
    height: 44,
    color: 'black',
    marginLeft: 33,
    marginRight: 34,
    width: 308,
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D0D5DD',
  },
  buttontext: {
    marginTop: 12,
    marginBottom: 12,
    textAlign: 'center',
    color: 'white',
    fontWeight: '600',
    fontSize: 23,
  },
  button: {
    backgroundColor: '#5B59FE',
    marginLeft: 33,
    marginRight: 34,
    marginTop: 24,
    borderRadius: 8,
  },
});

export default loginStyles;
