import {StyleSheet} from 'react-native';

const profileStyles = StyleSheet.create({
  firstRow: {
    flexDirection: 'row',
  },
  buttontext: {
    marginTop: 12,
    marginBottom: 12,
    textAlign: 'center',
    color: 'white',
    fontWeight: '600',
    fontSize: 23,
  },
  button: {
    backgroundColor: '#5B59FE',
    marginLeft: 33,
    marginRight: 34,
    marginTop: 225,
    borderRadius: 8,
  },
  inputemail: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 33,
    marginRight: 34,
    marginTop: 5,
    borderWidth: 1,
    width: 310,
    borderColor: '#D0D5DD',
    borderRadius: 8,
  },
  textemail: {
    color: '#121212',
    width: 40,
    marginTop: 24,
    marginLeft: 33,
    height: 20,
    fontFamily: 'Familjen Grotesk',
    lineHeight: 27.6,
    textAlign: 'center',
  },
  name: {
    color: '#344054',
    width: 40,
    marginTop: 69,
    marginLeft: 33,
    height: 20,
    fontFamily: 'Familjen Grotesk',
    lineHeight: 27.6,
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 14,
  },
  input1: {
    padding: 12,
    marginTop: 6,
    height: 44,
    marginLeft: 33,
    marginRight: 4,
    maxWidth: 500,
    width: 308,
    justifyContent: 'center',
    borderRadius: 8,
    color: 'black',
    borderWidth: 1,
    borderColor: '#D0D5DD',
  },
  mainHeading: {
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 28,
    marginLeft: 80,
    marginTop: 12,
    color: '#0F0F0F',
  },
  personpicture: {
    marginHorizontal: 125,
    width: 125,
    height: 125,
    marginTop: 16,
    borderRadius: 100,
  },
});
export default profileStyles;
